Fix typo in SetLowPowerDefault
oneapi-src/oneVPL-intel-gpu pull request #141
Opened 2021-07-20 08:15 UTC by ybakhano

2021-07-20 14:17 UTC, lakulako submitted a review, later dismissed

2021-07-21 08:53 UTC, ivan-losev requested changes

2021-07-21 08:53 UTC, ivan-losev commented on _studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp
> +        || platform == MFX_HW_EHL
Please, guard below code at line 2265 into {}
```
            unsupported = true;
            par.mfx.RateControlMethod = 0;
```

2021-07-21 09:06 UTC, lakulako commented on _studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp
> +    (void)platform; // fix wrn for non Gen11 build
Looks like (void)platform; is no more needed here.

2021-07-21 10:01 UTC, lakulako approved these changes

2021-07-21 10:04 UTC, ybakhano commented on _studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp
> +        || platform == MFX_HW_EHL
done

2021-07-21 10:05 UTC, ybakhano commented on _studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp
> +    (void)platform; // fix wrn for non Gen11 build
I suppose it can be done later

2021-07-21 10:13 UTC, ivan-losev approved these changes

2021-07-21 13:52 UTC, dmitryermilov approved these changes

2021-07-21 13:52 UTC, merged