[AVCe] Separate max and default active refs
oneapi-src/oneVPL-intel-gpu pull request #146
Opened 2021-07-20 14:36 UTC by lakulako

Can be different in future.

2021-07-27 13:48 UTC, ivan-losev requested changes

2021-07-27 13:48 UTC, ivan-losev commented on _studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp
>              { 0, 8, 6, 3, 3, 3, 1, 1 }, // VME progressive < 4k or interlaced (platform > MFX_HW_HSW_ULT)
Please, add new line between L926 and L927

2021-07-27 14:42 UTC, ivan-losev approved these changes

2021-07-28 09:39 UTC, dmitryermilov approved these changes

2021-07-28 11:34 UTC, merged