[Encode] code alignment
oneapi-src/oneVPL-intel-gpu pull request #150
Opened 2021-07-22 10:55 UTC by lwan108

Signed-off-by: LijuanWang <lijuan.wang@intel.com>

2021-07-22 14:22 UTC, dmitryermilov approved these changes

2021-07-22 14:46 UTC, vilichev submitted a review, later dismissed

2021-07-23 04:05 UTC, thomasli21801 submitted a review, later dismissed

2021-07-23 06:25 UTC, ansokolo approved these changes

2021-07-23 08:01 UTC, takulako commented on _studio/enctools/src/mfx_enctools_lpla.cpp
> +        m_extBufLPLA.codecTypeInEncodePass = ctrl.CodecId;
codecTypeInEncodePass  is currently missing in the OS version of mfxExtLplaParam struct  in mfx_ext_buffers.h.  I guess we'd better add it there to keep the code compilable with MFX_ENABLE_ENCTOOLS_LPLA defined.

2021-07-23 08:13 UTC, mgonchar requested changes

2021-07-23 08:13 UTC, mgonchar commented on _studio/mfx_lib/encode_hw/mpeg2/src/mfx_mpeg2_encode_utils_hw.cpp
> +
are we sure we can delete this?

2021-07-23 08:13 UTC, lwan108 commented on _studio/enctools/src/mfx_enctools_lpla.cpp
> +        m_extBufLPLA.codecTypeInEncodePass = ctrl.CodecId;
Thanks Timofei. Adding codecTypeInEncodePass in mfxExtLplaParam struct will be together with LPLA enabling on linux.

2021-07-23 08:16 UTC, lwan108 commented on _studio/mfx_lib/encode_hw/h264/include/mfx_h264_encode_hw_utils.h
>      public:
It's to align with latest close source code. @takulako , could you please comment which one is expected?

2021-07-23 08:18 UTC, lwan108 commented on _studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp
It's to align with latest close source code. Need to add this to close source code, if this is useful.

2021-07-23 08:18 UTC, lwan108 commented on _studio/mfx_lib/encode_hw/mpeg2/src/mfx_mpeg2_encode_utils_hw.cpp
> +
It's to align with latest close source code, no such code in CS.

2021-07-23 08:24 UTC, lwan108 commented on _studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_hw.cpp
>  {
To align with CS.

2021-07-23 08:25 UTC, lwan108 commented on _studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp
To align with CS.

2021-07-23 08:58 UTC, takulako commented on _studio/mfx_lib/encode_hw/h264/include/mfx_h264_encode_hw_utils.h
>      public:
The line was added in OS by @onabiull in April'21
SHA-1: 1a55c256657728fa76244134cc304fafd73ab91d
* Initial oneVPL GPU Runtime upstream

2021-07-26 02:54 UTC, lwan108 commented on _studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_hw.cpp
>  {
CS code was removed @4365da4, PR [1844](https://github.com/intel-innersource/drivers.gpu.media.sdk.lib/pull/1844 ).
@dmitryermilov

2021-07-26 02:54 UTC, lwan108 commented on _studio/mfx_lib/encode_hw/h264/include/mfx_h264_encode_hw_utils.h
>      public:
Thanks@takulako. Reverted OS removal, and added this in CS. @DenWolf pls comment if the change isn't expected.

2021-07-26 03:00 UTC, lwan108 commented on _studio/mfx_lib/encode_hw/mpeg2/src/mfx_mpeg2_encode_utils_hw.cpp
> +
CS SHA :0713bc98fe28124debcd221037878ecf15ebc67f, PR[1723](https://github.com/intel-innersource/drivers.gpu.media.sdk.lib/pull/1723), @AntonGrishin

2021-07-26 03:25 UTC, lwan108 commented on _studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp
CS SHA:2a2ac49e40472478e666082e6c3d1202affd43e4, PR[#1264](https://github.com/intel-innersource/drivers.gpu.media.sdk.lib/issues/1264),@saosipov

2021-07-26 03:31 UTC, lwan108 commented on _studio/mfx_lib/encode_hw/h264/include/mfx_h264_encode_hw_utils.h
>      public:
CS PR:[#2548](https://github.com/intel-innersource/drivers.gpu.media.sdk.lib/pull/2548)

2021-07-26 07:09 UTC, mgonchar commented on _studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_hw.cpp
>  {
ok, thanks

2021-07-26 07:11 UTC, mgonchar commented on _studio/mfx_lib/encode_hw/mpeg2/src/mfx_mpeg2_encode_utils_hw.cpp
> +
thanks for clarification!

2021-07-26 07:18 UTC, mgonchar commented on _studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp
got it, thanks

2021-07-26 07:32 UTC, mgonchar approved these changes

2021-07-26 08:58 UTC, thomasli21801 approved these changes

2021-07-26 09:02 UTC, dmitryermilov approved these changes

2021-07-26 09:19 UTC, ansokolo approved these changes

2021-07-26 09:48 UTC, takulako approved these changes

2021-07-26 09:54 UTC, ogolikov approved these changes

2021-07-26 09:59 UTC, merged