Update in-source project version
oneapi-src/oneVPL-intel-gpu pull request #19
Opened 2021-05-21 15:09 UTC by onabiull

2021-05-21 15:12 UTC, daleksan requested changes

2021-05-21 15:12 UTC, daleksan commented on CMakeLists.txt
> +set(MEDIA_VERSION  21.2.2) # auto-update
can you remove the space?

2021-05-24 07:52 UTC, onabiull commented on CMakeLists.txt
> +set(MEDIA_VERSION  21.2.2) # auto-update
done

2021-05-24 12:22 UTC, daleksan approved these changes

2021-05-24 15:08 UTC, dmitryermilov approved these changes

2021-05-24 15:08 UTC, merged