[core]: Enable 20 core on gen 12 and 12.2 platforms
oneapi-src/oneVPL-intel-gpu pull request #30
Opened 2021-06-03 11:12 UTC by alexelizarov

2021-06-08 13:22 UTC, dmitryermilov requested changes
waiting for val results

2021-06-09 09:08 UTC, mgonchar approved these changes
Val results looks good, no regressions

2021-06-09 09:55 UTC, onabiull approved these changes

2021-06-09 09:57 UTC, dmitryermilov approved these changes

2021-06-09 10:01 UTC, merged