Centralize feature macro def
oneapi-src/oneVPL-intel-gpu pull request #56
Opened 2021-06-15 11:02 UTC by wyc55069407

Move decode specific feature macro def into mfx_config_decode.
Setup stub mfx_config_encode and mfx_config_vpp

2021-06-16 01:23 UTC, lwan108 requested changes

2021-06-16 01:23 UTC, lwan108 commented on _studio/shared/umc/CMakeLists.txt
> +include(sources_ext.cmake OPTIONAL)
_ext.cmake is expected at the end of the file, after target_xxx.

2021-06-16 04:08 UTC, wyc55069407 commented on _studio/shared/umc/CMakeLists.txt
> +include(sources_ext.cmake OPTIONAL)
updated to move to end of file. Still working

2021-06-16 05:16 UTC, lwan108 approved these changes

2021-06-16 09:51 UTC, onabiull approved these changes

2021-06-17 05:45 UTC, onabiull approved these changes

2021-06-17 05:49 UTC, onabiull approved these changes

2021-06-17 05:51 UTC, merged