Core: partial clean up of OPAQ functions in CORE
oneapi-src/oneVPL-intel-gpu pull request #67
Opened 2021-06-21 16:29 UTC by mgonchar

This function causes WRN in clang12 build

2021-06-21 17:30 UTC, onabiull requested changes
I believe code would look clearer if we just drop this code instead of guarding it.

2021-06-22 07:53 UTC, mgonchar commented
Well @onabiull I agree that this code should be removed. But I don't want to remove it without all calling code removal (will be done in separate commit) and without removing all the rest OPAQ interfaces in CORE. This change was introduced to unblock #6 If we have several months to wait until proper clean up happens, we can postpone this change. Bu I think better to merge as is and clean up later

2021-06-22 08:46 UTC, onabiull approved these changes

2021-06-22 08:47 UTC, onabiull commented
Remove all opaque at once sounds good for me :)

2021-06-22 08:47 UTC, merged