Rename deprecated macros
oneapi-src/oneVPL-intel-gpu pull request #83
Opened 2021-07-01 02:33 UTC by yantangx

rename deprecated definition and parameters

Issue: N/A
Test: N/A
Signed-off-by: Ethan Wang <ethan.wang@intel.com>

2021-07-01 07:05 UTC, dmitryermilov requested changes

2021-07-01 07:05 UTC, dmitryermilov commented on _studio/mfx_lib/shared/include/mfx_h264_enc_common_hw.h
> +    static const mfxU16 MFX_RATECONTROL_Wireless_VBR = 100;
In capital, please

2021-07-01 07:05 UTC, dmitryermilov commented on _studio/shared/include/mfx_utils.h
> +    };
Please use definitions from public headers

2021-07-02 01:35 UTC, yantangx commented on _studio/mfx_lib/shared/include/mfx_h264_enc_common_hw.h
> +    static const mfxU16 MFX_RATECONTROL_Wireless_VBR = 100;
> In capital, please

sure

2021-07-02 01:36 UTC, yantangx commented on _studio/shared/include/mfx_utils.h
> +    };
> Please use definitions from public headers

sure, and this part will also be mark as false hit in IPLDT scan

2021-07-12 00:22 UTC, yantangx commented
this change is not needed. Reviewed IPLDT scan result, agreed to mark “GOOGLE” “Widevine” “PAVP” “decrypt” “Encrypted” as false hit.

2021-07-12 00:22 UTC, closed without merging