clean macro MFX_ONEVPL & API_USE_VPL
oneapi-src/oneVPL-intel-gpu pull request #97
Opened 2021-07-06 06:28 UTC by LesterMinGSE

2021-07-07 07:33 UTC, lwan108 requested changes

2021-07-07 07:33 UTC, lwan108 commented on builder/FindMFX.cmake
> +  INTERFACE MFX_ONEVPL
MFX_ONEVPL should be removed also.

2021-07-07 08:11 UTC, lwan108 submitted a review, later dismissed

2021-07-08 07:16 UTC, onabiull approved these changes

2021-07-13 06:28 UTC, lwan108 submitted a review, later dismissed

2021-07-27 04:54 UTC, lwan108 commented
Hi @LesterMinGSE, when can this be merged?

2021-07-27 09:10 UTC, onabiull approved these changes

2021-07-27 09:37 UTC, merged